# Generated by Django 3.0.3 on 2020-05-07 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magasin', '0005_auto_20200505_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='Date',
            field=models.DateField(default=datetime.date(2020, 5, 7)),
        ),
    ]
