# Generated by Django 3.0.3 on 2020-05-03 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.FloatField(default=0.0)),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=255)),
                ('prix', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Panier_has_Produits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField(default=0)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Magasin.Panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Magasin.Produit')),
            ],
        ),
        migrations.AddField(
            model_name='panier',
            name='Produits',
            field=models.ManyToManyField(default=None, through='Magasin.Panier_has_Produits', to='Magasin.Produit'),
        ),
    ]
