# Generated by Django 3.0.3 on 2020-05-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magasin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.FloatField(default=0.0),
        ),
    ]
