# Generated by Django 3.0.3 on 2020-05-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magasin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier_has_produits',
            name='quantite',
            field=models.FloatField(),
        ),
    ]
