# Generated by Django 3.0.3 on 2020-05-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magasin', '0003_panier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier',
            old_name='idClient',
            new_name='Client',
        ),
        migrations.AlterField(
            model_name='panier',
            name='Produits',
            field=models.ManyToManyField(default=None, to='Magasin.Produit'),
        ),
    ]
