# Generated by Django 3.0.5 on 2020-05-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magasin', '0003_auto_20200504_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='Total',
        ),
    ]
