# Generated by Django 3.0.6 on 2020-05-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magasin', '0008_auto_20200507_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='cX',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='commande',
            name='cY',
            field=models.FloatField(default=0.0),
        ),
    ]
