# Generated by Django 3.0.5 on 2020-05-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connexion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='ville',
            field=models.CharField(default='Paris', help_text='Ville', max_length=200),
            preserve_default=False,
        ),
    ]
