# Generated by Django 3.0.3 on 2020-05-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magasin', '0002_auto_20200504_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier_has_produits',
            name='quantite',
            field=models.IntegerField(),
        ),
    ]
