# Generated by Django 3.0.3 on 2020-05-07 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Magasin', '0007_auto_20200507_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
