# Generated by Django 3.0.3 on 2020-05-03 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codePostal', models.IntegerField(help_text='Code Postal')),
                ('adresse', models.CharField(help_text='Adresse', max_length=200)),
                ('nbPersonne', models.IntegerField(help_text='Nombre de personne dans le foyer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
