# Generated by Django 3.0.5 on 2020-05-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connexion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='nbPersonne',
            field=models.IntegerField(default=2, help_text='Nombre de personne dans le foyer'),
            preserve_default=False,
        ),
    ]
