# Generated by Django 3.0.5 on 2020-05-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connexion', '0003_auto_20200504_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='coordonneeGeoX',
            field=models.FloatField(help_text='Coordonnée en X'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='coordonneeGeoY',
            field=models.FloatField(help_text='Coordonnée en X'),
        ),
    ]
